# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2-libdb, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2-libdb
    version: 5.3.28
source:
    md5: 1fe34958058be563736c8fb7f205a10e
    url: http://msys2-sources.continuum.io/msys2-sources/msys/sources/libdb-5.3.28-2.src.tar.gz
build:
    number: '3'
    string: '3'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
        - m2-gcc-libs
        - m2-msys2-runtime
about:
    home: http://www.oracle.com/technology/software/products/berkeley-db/index.html
    license: GPL, custom
    summary: The Berkeley DB embedded database system
extra:
    msys2-binaries:
        win-32:
            md5: a23f958c1cfa633b3607e2c2022bcc95
            mv-dsts:
                - Library/
            mv-srcs:
                - '*'
            srcpkg: msys/libdb
            url: http://msys2-sources.continuum.io/msys2-sources/msys/i686/libdb-5.3.28-2-i686.pkg.tar.xz
        win-64:
            md5: d475807dbef95e592f2b46af5a82bad4
            mv-dsts:
                - Library/
            mv-srcs:
                - '*'
            srcpkg: msys/libdb
            url: http://msys2-sources.continuum.io/msys2-sources/msys/x86_64/libdb-5.3.28-2-x86_64.pkg.tar.xz
