# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2-gcc-libs, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2-gcc-libs
    version: 5.3.0
source:
    md5: ba851b68970752cb866e3031f1abca70
    url: http://msys2-sources.continuum.io/msys2-sources/msys/sources/gcc-libs-5.3.0-3.src.tar.gz
build:
    number: '4'
    string: '4'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
        - m2-msys2-runtime
about:
    home: http://gcc.gnu.org
    license: GPL, LGPL, FDL, custom
    summary: Runtime libraries shipped by GCC
extra:
    msys2-binaries:
        win-32:
            md5: 132521776fb451d5143b09a3334023c5
            mv-dsts:
                - Library/
            mv-srcs:
                - '*'
            srcpkg: msys/gcc-libs
            url: http://msys2-sources.continuum.io/msys2-sources/msys/i686/gcc-libs-5.3.0-3-i686.pkg.tar.xz
        win-64:
            md5: b38351b395ee8da2bd6a5d396bd656d4
            mv-dsts:
                - Library/
            mv-srcs:
                - '*'
            srcpkg: msys/gcc-libs
            url: http://msys2-sources.continuum.io/msys2-sources/msys/x86_64/gcc-libs-5.3.0-3-x86_64.pkg.tar.xz
