# c_compiler_version:      # [linux and not ppc64le]
#   - 5.4                  # [linux and not ppc64le]
# cxx_compiler_version:    # [linux and not ppc64le]
#   - 5.4                  # [linux and not ppc64le]
cudatoolkit:
  - 9.0
r_implementation:
  - r-base
  - mro-base  # [not osx and not linux32 and not win32]
skip_r_bindings: True   # [s390x or ppc64le or aarch64 or osx or win]
