# This file created by conda-build 3.23.3
# ------------------------------------------------

package:
  name: libxgboost
  version: 1.7.3
source:
  git_rev: v1.7.3
  git_url: https://github.com/dmlc/xgboost
  patches:
    - 0001-conda-Unbundle-libxgboost.-dll-dylib-so-WINDOWS.patch
build:
  activate_in_script: true
  ignore_run_exports: null
  missing_dso_whitelist: null
  number: 0
  string: hd77b12b_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - cmake 3.22.1 h9ad04ae_0
    - git 2.34.1 haa95532_0
    - libuv 1.40.0 he774522_0
    - lz4-c 1.9.4 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.2 h19a0ad4_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
about:
  description: 'XGBoost is an optimized distributed gradient boosting library designed
    to be highly efficient,

    flexible and portable. It implements machine learning algorithms under the Gradient
    Boosting

    framework. XGBoost provides a parallel tree boosting (also known as GBDT, GBM)
    that solve many

    data science problems in a fast and accurate way. The same code runs on major
    distributed

    environment (Hadoop, SGE, MPI) and can solve problems beyond billions of examples.

    '
  dev_url: https://github.com/dmlc/xgboost/
  doc_url: https://xgboost.readthedocs.io/
  home: https://github.com/dmlc/xgboost
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Scalable, Portable and Distributed Gradient Boosting (GBDT, GBRT or GBM)
    Library, for

    Python, R, Java, Scala, C++ and more. Runs on single machine, Hadoop, Spark, Flink

    and DataFlow

    '
extra:
  copy_test_source_files: true
  feedstock-name: xgboost
  final: true
  recipe-maintainers:
    - aldanor
    - fhoehle
    - jakirkham
    - ksangeek
    - xhochy
