# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_63cyjj1grl\clone\recipe, last modified Tue Feb 21 17:57:22 2023
# ------------------------------------------------

package:
  name: libgd
  version: 2.3.3
source:
  patches:
    - patches/linux-fontconfig-basic.patch
  sha256: dd3f1f0bb016edcc0b2d082e8229c822ad1d02223511997c80461481759b1ed2
  url: https://github.com/libgd/libgd/releases/download/gd-2.3.3/libgd-2.3.3.tar.gz
build:
  number: '2'
  run_exports:
    - libgd >=2.3.3,<2.4.0a0
  string: hd77b12b_2
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - cmake 3.22.1 h9ad04ae_0
    - glib 2.69.1 h5dc1a3c_2
    - libffi 3.4.2 hd77b12b_6
    - libiconv 1.16 h2bbff1b_2
    - libuv 1.40.0 he774522_0
    - lz4-c 1.9.4 h2bbff1b_0
    - m2-bash 4.3.042 5
    - m2-gawk 4.1.3 2
    - m2-gcc-libs 5.3.0 4
    - m2-gmp 6.1.0 3
    - m2-libiconv 1.14 3
    - m2-libintl 0.19.7 4
    - m2-libreadline 6.3.008 8
    - m2-mpfr 3.1.4 2
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-ncurses 6.0.20160220 2
    - m2-patch 2.7.5 2
    - m2-sed 4.2.2 3
    - msys2-conda-epoch 20160418 1
    - ninja-base 1.10.2 h6d14046_5
    - pcre 8.45 hd77b12b_0
    - pkg-config 0.29.2 h8cc25b3_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.2 h19a0ad4_0
  host:
    - expat 2.4.9 h6c2663c_0
    - fontconfig 2.14.1 hc0defaf_1
    - freetype 2.10.4 hd328e21_0
    - icu 58.2 ha925a31_3
    - jpeg 9e h2bbff1b_0
    - libiconv 1.16 h2bbff1b_2
    - libpng 1.6.37 h2a8f88b_0
    - libtiff 4.1.0 h8a3f274_2
    - libwebp 1.2.4 h2bbff1b_0
    - libwebp-base 1.2.4 h2bbff1b_0
    - libxml2 2.9.14 h0ad7f3c_0
    - lz4-c 1.9.4 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.2 h19a0ad4_0
  run:
    - expat >=2.4.9,<3.0a0
    - fontconfig >=2.14.1,<3.0a0
    - freetype >=2.10.4,<3.0a0
    - icu >=58.0,<59.0a0
    - icu >=58.2,<59.0a0
    - jpeg >=9e,<10a
    - libpng >=1.6.37,<1.7.0a0
    - libtiff >=4.1.0,<5.0a0
    - libwebp >=1.2.0,<1.3.0a0
    - libwebp-base >=1.2.4,<2.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - if not exist %PREFIX%\\Library\\bin\\libgd.dll exit 1
    - if not exist %PREFIX%\\Library\\lib\\libgd.lib exit 1
about:
  description: 'GD is commonly used to generate charts, graphics, thumbnails, and
    most anything else, on the fly.

    It is lite weight and fits usages like web development, embemdedded, or any other
    usages you may need.

    It supports transparency, blending, images transformations and various filters.

    Its design allows the additions of custom features in a very friendly manner.

    '
  dev_url: https://github.com/libgd/libgd
  doc_url: https://libgd.github.io/pages/docs.html
  home: https://libgd.github.io/
  license: GD
  license_family: BSD
  license_file: COPYING
  summary: Library for the dynamic creation of images.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 63a8f10a-a2de-4a22-aef9-6d3b4e3c1797
  recipe-maintainers:
    - ChrisBarker-NOAA
    - croth1
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/libgd-feedstock.git
  sha: 6534bc5cf13267ac99f8b9b0894143f78207ee77
