# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# C:\Users\ray\conda\conda-recipes\msys2\m2-icu, last modified Mon Dec 19 01:03:46 2016
# ------------------------------------------------

package:
    name: m2-icu
    version: '56.1'
source:
    md5: 067a6c715e5c087246b8c69c31ea6aea
    url: http://msys2-sources.continuum.io/msys2-sources/msys/sources/icu-56.1-1.src.tar.gz
build:
    number: '2'
    string: '2'
requirements:
    build: []
    run:
        - msys2-conda-epoch >=20160418
        - m2-gcc-libs
about:
    home: http://www.icu-project.org/
    license: GPL, custom:"icu"
    summary: International Components for Unicode library
extra:
    msys2-binaries:
        win-32:
            md5: c3c6e56c42803c8ccdb76a50b2d54a65
            mv-dsts:
                - Library/
            mv-srcs:
                - '*'
            srcpkg: msys/icu
            url: http://msys2-sources.continuum.io/msys2-sources/msys/i686/icu-56.1-1-i686.pkg.tar.xz
        win-64:
            md5: 8fe156ae5aeff60981ea3513fbaeec92
            mv-dsts:
                - Library/
            mv-srcs:
                - '*'
            srcpkg: msys/icu
            url: http://msys2-sources.continuum.io/msys2-sources/msys/x86_64/icu-56.1-1-x86_64.pkg.tar.xz
