# This file created by conda-build 3.21.9
# ------------------------------------------------

package:
  name: libboost
  version: 1.73.0
source:
  patches:
    - 0001-CONDA_BUILD-customization.patch
    - 0002-boost.python-fix-python-lib-config-abiflags.patch
    - 0003-boost.python-fix-unix-library-paths-and-darwin-sysroot.patch
    - 0004-patch-clang_version.patch
    - 0005-boost.python-add-Library-include-and-lib-on-Win.patch
    - 0006-boost.python-py-fopen-private.patch
  sha256: 4eb3b8d442b426dc35346235c8733b5ae35ba431690e38c6a8263dce9fcbb402
  url: https://boostorg.jfrog.io/artifactory/main/release/1.73.0/source/boost_1_73_0.tar.bz2
build:
  activate_in_script: true
  missing_dso_whitelist: null
  number: 12
  script_env:
    - CONDA_BUILD_DEBUG_BUILD_SYSTEM=no
  string: h6c2663c_12
requirements:
  build:
    - ccache 3.7.9 h1c70317_0
    - m2-coreutils 8.25 102
    - m2-gcc-libs 5.3.0 4
    - m2-gmp 6.1.0 3
    - m2-libiconv 1.14 3
    - m2-libintl 0.19.7 4
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2w64-gcc-libgfortran 5.3.0 6
    - m2w64-gcc-libs 5.3.0 7
    - m2w64-gcc-libs-core 5.3.0 7
    - m2w64-gmp 6.1.0 2
    - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
    - msys2-conda-epoch 20160418 1
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - lz4-c 1.9.3 h2bbff1b_1
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - xz 5.2.5 h8cc25b3_1
    - zlib 1.2.12 h8cc25b3_2
    - zstd 1.5.2 h19a0ad4_0
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - xz >=5.2.5,<6.0a0
    - zlib >=1.2.12,<1.3.0a0
    - zstd >=1.5.2,<1.6.0a0
test:
  commands:
    - b2 --help
    - bjam --help
    - pushd tests
    - pushd hello_world_cxx
    - test.bat
    - popd
    - popd
    - if exist %PREFIX%\Library\include\boost\boost\python.hpp exit 1
    - if exist %PREFIX%\Library\include\boost\python exit 1
    - if not exist %PREFIX%\Library\include\boost\assert.hpp exit 1
    - if not exist %PREFIX%\Library\bin\boost_atomic.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_atomic.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_chrono.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_chrono.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_container.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_container.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_context.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_context.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_coroutine.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_coroutine.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_date_time.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_date_time.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_filesystem.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_filesystem.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_graph.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_graph.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_iostreams.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_iostreams.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_locale.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_locale.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_log.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_log.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_log_setup.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_log_setup.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_math_c99.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_math_c99.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_math_c99f.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_math_c99f.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_math_c99l.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_math_c99l.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_math_tr1.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_math_tr1.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_math_tr1f.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_math_tr1f.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_math_tr1l.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_math_tr1l.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_prg_exec_monitor.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_prg_exec_monitor.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_program_options.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_program_options.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_random.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_random.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_regex.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_regex.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_serialization.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_serialization.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_system.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_system.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_thread.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_thread.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_timer.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_timer.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_type_erasure.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_type_erasure.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_unit_test_framework.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_unit_test_framework.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_wave.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_wave.lib exit 1
    - if not exist %PREFIX%\Library\bin\boost_wserialization.dll exit 1
    - if not exist %PREFIX%\Library\lib\boost_wserialization.lib exit 1
  files:
    - tests
  requires:
    - ripgrep
    - vs2017_win-64
about:
  dev_url: https://www.boost.org/doc/libs/1_73_0/more/getting_started/index.html
  doc_url: https://www.boost.org/doc/libs/1_73_0/
  home: https://www.boost.org/
  license: BSL-1.0
  license_family: OTHER
  license_file: LICENSE_1_0.txt
  summary: Free peer-reviewed portable C++ source libraries.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - isuruf
    - jakirkham
    - jschueller
    - mingwandroid
    - msarahan
    - ocefpaf
    - scopatz
